// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw00wcZ04O9z8ttMkB50VAi-fUL3l3u8U',
    appId: '1:341395595935:web:77cf24d5c1a1c8213878aa',
    messagingSenderId: '341395595935',
    projectId: 'fasum-268b8',
    authDomain: 'fasum-268b8.firebaseapp.com',
    storageBucket: 'fasum-268b8.appspot.com',
    measurementId: 'G-06XJL9M881',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgx4WVz7HIYznfnuI4rvOpnex0b49R7IM',
    appId: '1:341395595935:android:9d8636a542dd0db73878aa',
    messagingSenderId: '341395595935',
    projectId: 'fasum-268b8',
    storageBucket: 'fasum-268b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASVtKnCHrkxEjPDJsYVd6lhmoJfMyt7eU',
    appId: '1:341395595935:ios:5df286ed8f04217c3878aa',
    messagingSenderId: '341395595935',
    projectId: 'fasum-268b8',
    storageBucket: 'fasum-268b8.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASVtKnCHrkxEjPDJsYVd6lhmoJfMyt7eU',
    appId: '1:341395595935:ios:ca105c1d4cfd81263878aa',
    messagingSenderId: '341395595935',
    projectId: 'fasum-268b8',
    storageBucket: 'fasum-268b8.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
